version: '3.8'

volumes:
  composer-vol:

services:
  frontend:
    build:
      context: ./dashboard-app
    container_name: dashboard-app
    restart: unless-stopped
    ports:
      - "8080:3000"

networks:
  app-network:
    driver: bridge
  db: