# docker-compose.yml
version: "3.8"
services:
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src/backend-portal:/var/www/html/backend-portal
    working_dir: /var/www/html/backend-portal

  composer:
    container_name: composer
    image: composer/composer
    volumes:
      - ./src/backend-portal:/var/www/html/backend-portal
    working_dir: /var/www/html/backend-portal
    command: install

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '<root-password>'
      MYSQL_DATABASE: 'portal-db'
      MYSQL_USER: 'portal-db-user'
      MYSQL_PASSWORD: 'portal-db-password'
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80

  frontend:
    build:
      context: ./dashboard-app
    container_name: dashboard-app
    restart: unless-stopped
#    volumes:
#      - /app/build:/usr/share/nginx/html
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
      - frontend
    ports:
      - "8000:80"
#      - "8080:3000"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src/backend-portal:/var/www/html/backend-portal
#      - /app/build:/usr/share/nginx/html
